name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Make Maven Wrapper Executable
      run: chmod +x mvnw

    - name: Build and Test with Maven
      run: ./mvnw -B clean verify

    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-coverage-report
        path: target/site/jacoco/
